version: '3'
services:
  arena-app-dev:
    image: "tc-arena-app:latest"
    volumes:
      - ./env/dev:/home/apps/env
    command: ["/home/apps/start-services.sh", "app"]
    ports:
      - "5001:5001"
      - "5003:5003"
      - "5016:5016"
      - "5037:5037"
  arena-processor-dev:
    image: "tc-arena-app:latest"
    volumes:
      - ./env/dev:/home/apps/env
    command: ["/home/apps/start-services.sh", "processor"]
    environment:
      - PROCESSOR_OPTS=-Darena.processor-queues=practice,compile,srm-test,admin-test,mm-test -Darena.processor-default-timeout=5