version: '3'
services:
  arena-informix:
    image: "appiriodevops/tc-database-scripts:latest"
    platform: linux/amd64
    hostname: informix.cloud.topcoder.com
    container_name: arena-informix
    environment:
      LICENSE: accept
    ports:
      - "2021:2021"
    tty: true
  arena-mysql:
    image: mysql:5.7
    cap_add:
      - SYS_NICE
    volumes:
      - ./mysql-files:/docker-entrypoint-initdb.d
    container_name: arena-mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: farm
      MYSQL_PASSWORD: farmpass
      MYSQL_DATABASE: farm
    ports:
      - "3306:3306"
  arena-ldap:
    container_name: arena-ldap
    build:
      context: ./
      dockerfile: Dockerfile_ldap
    ports:
      - "389:389"
  arena-sqs:
    container_name: arena-sqs
    build:
      context: ./
      dockerfile: Dockerfile_sqs
    ports:
      - "9324:9324"
  mock-tc-api:
    container_name: mock-tc-api
    build:
      context: ./
      dockerfile: Dockerfile_tc_api
    ports:
      - "8081:8081"
  arena-app:
    depends_on:
      - arena-informix
      - arena-mysql
      - arena-ldap
      - arena-sqs
      - mock-tc-api
    container_name: "arena-app"
    build:
      context: ./
    ports:
      - "5001:5001"
      - "5003:5003"
      - "5016:5016"
      - "5037:5037"