version: '3'
services:
  arena-app-dev:
    image: "arena-app:dev"
    container_name: "arena-app-dev"
    build:
      context: ./
      dockerfile: ECSDockerfile
    ports:
      - "5001:5001"
      - "5003:5003"
      - "5016:5016"
      - "5037:5037"