version: '3'
services:
  arena-informix:
    image: "appiriodevops/tc-database-scripts:latest"
    platform: linux/amd64
    hostname: informix.cloud.topcoder.com
    container_name: arena-db
    environment:
      LICENSE: accept
    ports:
      - "2021:2021"
      - "2022:2022"
      - "27017:27017"
      - "27018:27018"
      - "27883:27883"
    tty: true
  arena-mysql:
    image: mysql:5.7
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: farm
      MYSQL_PASSWORD: farmpass
      MYSQL_DATABASE: farm
    ports:
      - "3306:3306"
  arena-app:
    image: "arena-app:latest"
    depends_on:
      - arena-informix
      - arena-mysql
    container_name: "arena-app"
    build:
      context: ./
    ports:
      - "5016:5016"
      - "9324:9324"
      - "5037:5037"
      - "5003:5003"
      - "5002:5002"