/* Generated By:JJTree: Do not edit this line. ASTBytes.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTBytes extends SimpleNode {
  public ASTBytes(int id) {
    super(id);
  }

  public ASTBytes(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
