/* Generated By:JJTree: Do not edit this line. ASTExportAttr.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTExportAttr extends SimpleNode {
  public ASTExportAttr(int id) {
    super(id);
  }

  public ASTExportAttr(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
