/* Generated By:JJTree: Do not edit this line. ASTExternSourceDecl.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTExternSourceDecl extends SimpleNode {
  public ASTExternSourceDecl(int id) {
    super(id);
  }

  public ASTExternSourceDecl(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
