/* Generated By:JJTree: Do not edit this line. ASTGenPars.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTGenPars extends SimpleNode {
  public ASTGenPars(int id) {
    super(id);
  }

  public ASTGenPars(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
