/* Generated By:JJTree: Do not edit this line. ASTHandlerBlock.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTHandlerBlock extends SimpleNode {
  public ASTHandlerBlock(int id) {
    super(id);
  }

  public ASTHandlerBlock(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
