/* Generated By:JJTree: Do not edit this line. ASTMethAttr.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTMethAttr extends SimpleNode {
  public ASTMethAttr(int id) {
    super(id);
  }

  public ASTMethAttr(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
