/* Generated By:JJTree: Do not edit this line. ASTSecAction.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTSecAction extends SimpleNode {
  public ASTSecAction(int id) {
    super(id);
  }

  public ASTSecAction(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
