/* Generated By:JJTree: Do not edit this line. ASTTryBlock.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTTryBlock extends SimpleNode {
  public ASTTryBlock(int id) {
    super(id);
  }

  public ASTTryBlock(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
