/* Generated By:JJTree: Do not edit this line. ASTTypeReference.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTTypeReference extends SimpleNode {
  public ASTTypeReference(int id) {
    super(id);
  }

  public ASTTypeReference(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String getType() {
      //check this value
      String ret = "";
      for(int i = 0; i < this.jjtGetNumChildren(); i++) {
        SimpleNode n = (SimpleNode)this.jjtGetChild(i);
        if(n instanceof ASTDottedName) {
            if(!ret.equals("")) {
                ret += ".";
            }
            ret += ((ASTDottedName)n).getName();
        }
      }
      
      if(ret.equals(""))
        return null;
      
      return ret;
  }
}
