/* Generated By:JJTree: Do not edit this line. ASTVTFixupDecl.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTVTFixupDecl extends SimpleNode {
  public ASTVTFixupDecl(int id) {
    super(id);
  }

  public ASTVTFixupDecl(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
