/* Generated By:JJTree: Do not edit this line. ASTAssemblyRefName.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTAssemblyRefName extends SimpleNode {
  public ASTAssemblyRefName(int id) {
    super(id);
  }

  public ASTAssemblyRefName(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
