/* Generated By:JJTree: Do not edit this line. ASTDdItem.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTDdItem extends SimpleNode {
  public ASTDdItem(int id) {
    super(id);
  }

  public ASTDdItem(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
