/* Generated By:JJTree: Do not edit this line. ASTFloat64.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTFloat64 extends SimpleNode {
  public ASTFloat64(int id) {
    super(id);
  }

  public ASTFloat64(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
