/* Generated By:JJTree: Do not edit this line. ASTGenArgs.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTGenArgs extends SimpleNode {
  public ASTGenArgs(int id) {
    super(id);
  }

  public ASTGenArgs(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
