/* Generated By:JJTree: Do not edit this line. ASTImplAttr.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTImplAttr extends SimpleNode {
  public ASTImplAttr(int id) {
    super(id);
  }

  public ASTImplAttr(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
