/* Generated By:JJTree: Do not edit this line. ASTManResDecl.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTManResDecl extends SimpleNode {
  public ASTManResDecl(int id) {
    super(id);
  }

  public ASTManResDecl(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
