/* Generated By:JJTree: Do not edit this line. ASTParamAttr.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTParamAttr extends SimpleNode {
  public ASTParamAttr(int id) {
    super(id);
  }

  public ASTParamAttr(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
