/* Generated By:JJTree: Do not edit this line. ASTSecurityDecl.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTSecurityDecl extends SimpleNode {
  public ASTSecurityDecl(int id) {
    super(id);
  }

  public ASTSecurityDecl(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
