/* Generated By:JJTree: Do not edit this line. .\MSILParserTreeConstants.java */

package com.topcoder.services.compiler.util.MSILParser;

public interface MSILParserTreeConstants
{
  public int JJTILFILE = 0;
  public int JJTID = 1;
  public int JJTDOTTEDNAME = 2;
  public int JJTLABELOROFFSET = 3;
  public int JJTLABELS = 4;
  public int JJTCODELABEL = 5;
  public int JJTDATALABEL = 6;
  public int JJTBYTES = 7;
  public int JJTFLOAT32 = 8;
  public int JJTFLOAT64 = 9;
  public int JJTEXTERNSOURCEDECL = 10;
  public int JJTFILENAME = 11;
  public int JJTDECL = 12;
  public int JJTCLASS = 13;
  public int JJTLANGUAGEDECL = 14;
  public int JJTSECURITYDECL = 15;
  public int JJTNAMEVALPAIRS = 16;
  public int JJTNAMEVALPAIR = 17;
  public int JJTSECACTION = 18;
  public int JJTVTFIXUPDECL = 19;
  public int JJTVTFIXUPATTR = 20;
  public int JJTMANRESDECL = 21;
  public int JJTLOCALSSIGNATURE = 22;
  public int JJTLOCAL = 23;
  public int JJTINSTR = 24;
  public int JJTMETHODCALL = 25;
  public int JJTINSTR_TOK = 26;
  public int JJTINSTR_TYPE = 27;
  public int JJTINSTR_FIELD = 28;
  public int JJTINSTR_METHOD = 29;
  public int JJTINSTR_BR = 30;
  public int JJTINSTR_R = 31;
  public int JJTINSTR_I = 32;
  public int JJTINSTR_VAR = 33;
  public int JJTINSTR_NONE = 34;
  public int JJTSCOPEBLOCK = 35;
  public int JJTSEHBLOCK = 36;
  public int JJTTRYBLOCK = 37;
  public int JJTSEHCLAUSE = 38;
  public int JJTHANDLERBLOCK = 39;
  public int JJTFIELDINIT = 40;
  public int JJTMETHODBODYITEM = 41;
  public int JJTMETHODHEADER = 42;
  public int JJTPINVATTR = 43;
  public int JJTMETHATTR = 44;
  public int JJTIMPLATTR = 45;
  public int JJTFIELDDECL = 46;
  public int JJTFIELDATTR = 47;
  public int JJTDATADECL = 48;
  public int JJTDDBODY = 49;
  public int JJTDDITEMLIST = 50;
  public int JJTDDITEM = 51;
  public int JJTCUSTOMDECL = 52;
  public int JJTCTOR = 53;
  public int JJTEXPORTATTR = 54;
  public int JJTEXTERNCLASSDECL = 55;
  public int JJTCLASSHEADER = 56;
  public int JJTCLASSNAME = 57;
  public int JJTGENPARS = 58;
  public int JJTGENPAR = 59;
  public int JJTGENPARATTRIBS = 60;
  public int JJTGENCONSTRAINTS = 61;
  public int JJTCLASSATTR = 62;
  public int JJTCLASSMEMBER = 63;
  public int JJTGENARITY = 64;
  public int JJTPROPHEADER = 65;
  public int JJTPROPMEMBER = 66;
  public int JJTMETHODNAME = 67;
  public int JJTEVENTHEADER = 68;
  public int JJTEVENTMEMBER = 69;
  public int JJTASMREFDECL = 70;
  public int JJTASMDECL = 71;
  public int JJTTYPE = 72;
  public int JJTTYPEBASE = 73;
  public int JJTINSPECTABLETYPE = 74;
  public int JJTTYPEBASE2 = 75;
  public int JJTTYPESPEC = 76;
  public int JJTBOUND = 77;
  public int JJTGENARGS = 78;
  public int JJTPARAMETERS = 79;
  public int JJTPARAM = 80;
  public int JJTPARAMATTR = 81;
  public int JJTCALLCONV = 82;
  public int JJTCALLKIND = 83;
  public int JJTTYPEREFERENCE = 84;
  public int JJTRESOLUTIONSCOPE = 85;
  public int JJTASSEMBLYREFNAME = 86;
  public int JJTNATIVETYPE = 87;
  public int JJTVALUETYPEREFERENCE = 88;
  public int JJTFIELD = 89;
  public int JJTINT32 = 90;
  public int JJTHEXBYTE = 91;
  public int JJTREALNUMBER = 92;


  public String[] jjtNodeName = {
    "ILFile",
    "Id",
    "DottedName",
    "LabelOrOffset",
    "Labels",
    "CodeLabel",
    "DataLabel",
    "Bytes",
    "Float32",
    "Float64",
    "ExternSourceDecl",
    "Filename",
    "Decl",
    "Class",
    "LanguageDecl",
    "SecurityDecl",
    "NameValPairs",
    "NameValPair",
    "SecAction",
    "VTFixupDecl",
    "VTFixupAttr",
    "ManResDecl",
    "LocalsSignature",
    "Local",
    "Instr",
    "MethodCall",
    "Instr_Tok",
    "Instr_Type",
    "Instr_Field",
    "Instr_Method",
    "Instr_Br",
    "Instr_R",
    "Instr_I",
    "Instr_Var",
    "Instr_None",
    "ScopeBlock",
    "SEHBlock",
    "TryBlock",
    "SEHClause",
    "HandlerBlock",
    "FieldInit",
    "MethodBodyItem",
    "MethodHeader",
    "PinvAttr",
    "MethAttr",
    "ImplAttr",
    "FieldDecl",
    "FieldAttr",
    "DataDecl",
    "DdBody",
    "DdItemList",
    "DdItem",
    "CustomDecl",
    "Ctor",
    "ExportAttr",
    "ExternClassDecl",
    "ClassHeader",
    "ClassName",
    "GenPars",
    "GenPar",
    "GenParAttribs",
    "GenConstraints",
    "ClassAttr",
    "ClassMember",
    "GenArity",
    "PropHeader",
    "PropMember",
    "MethodName",
    "EventHeader",
    "EventMember",
    "AsmRefDecl",
    "AsmDecl",
    "Type",
    "TypeBase",
    "InspectableType",
    "TypeBase2",
    "TypeSpec",
    "Bound",
    "GenArgs",
    "Parameters",
    "Param",
    "ParamAttr",
    "CallConv",
    "CallKind",
    "TypeReference",
    "ResolutionScope",
    "AssemblyRefName",
    "NativeType",
    "ValueTypeReference",
    "Field",
    "Int32",
    "HexByte",
    "RealNumber",
  };
}
