/* Generated By:JJTree: Do not edit this line. ASTAsmRefDecl.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTAsmRefDecl extends SimpleNode {
  public ASTAsmRefDecl(int id) {
    super(id);
  }

  public ASTAsmRefDecl(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
