/* Generated By:JJTree: Do not edit this line. ASTAsmDecl.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTAsmDecl extends SimpleNode {
  public ASTAsmDecl(int id) {
    super(id);
  }

  public ASTAsmDecl(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
