/* Generated By:JJTree: Do not edit this line. ASTBound.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTBound extends SimpleNode {
  public ASTBound(int id) {
    super(id);
  }

  public ASTBound(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
