/* Generated By:JJTree: Do not edit this line. ASTCallConv.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTCallConv extends SimpleNode {
  public ASTCallConv(int id) {
    super(id);
  }

  public ASTCallConv(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
