/* Generated By:JJTree: Do not edit this line. ASTClassHeader.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTClassHeader extends SimpleNode {
  public ASTClassHeader(int id) {
    super(id);
  }

  public ASTClassHeader(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
