/* Generated By:JJTree: Do not edit this line. ASTCtor.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTCtor extends SimpleNode {
  public ASTCtor(int id) {
    super(id);
  }

  public ASTCtor(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
