/* Generated By:JJTree: Do not edit this line. ASTCustomDecl.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTCustomDecl extends SimpleNode {
  public ASTCustomDecl(int id) {
    super(id);
  }

  public ASTCustomDecl(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
