/* Generated By:JJTree: Do not edit this line. ASTClassAttr.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTClassAttr extends SimpleNode {
  public ASTClassAttr(int id) {
    super(id);
  }

  public ASTClassAttr(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
