/* Generated By:JJTree: Do not edit this line. ASTDdItemList.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTDdItemList extends SimpleNode {
  public ASTDdItemList(int id) {
    super(id);
  }

  public ASTDdItemList(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
