/* Generated By:JJTree: Do not edit this line. ASTDataDecl.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTDataDecl extends SimpleNode {
  public ASTDataDecl(int id) {
    super(id);
  }

  public ASTDataDecl(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
