/* Generated By:JJTree: Do not edit this line. ASTDataLabel.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTDataLabel extends SimpleNode {
  public ASTDataLabel(int id) {
    super(id);
  }

  public ASTDataLabel(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
