/* Generated By:JJTree: Do not edit this line. ASTDottedName.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTDottedName extends SimpleNode {
  public ASTDottedName(int id) {
    super(id);
  }

  public ASTDottedName(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  private String name = null;
  
  public void setName(String s) {
      this.name = s;
  }
  
  public String getName() {
      if(name != null)
        return name;
      
      //get it from the Id node below
      return ((ASTId)this.children[0]).getName();
  }
}
