/* Generated By:JJTree: Do not edit this line. ASTEventMember.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTEventMember extends SimpleNode {
  public ASTEventMember(int id) {
    super(id);
  }

  public ASTEventMember(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
