/* Generated By:JJTree: Do not edit this line. ASTFieldDecl.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTFieldDecl extends SimpleNode {
  public ASTFieldDecl(int id) {
    super(id);
  }

  public ASTFieldDecl(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
