/* Generated By:JJTree: Do not edit this line. ASTFieldAttr.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTFieldAttr extends SimpleNode {
  public ASTFieldAttr(int id) {
    super(id);
  }

  public ASTFieldAttr(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
