/* Generated By:JJTree: Do not edit this line. ASTGenArity.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTGenArity extends SimpleNode {
  public ASTGenArity(int id) {
    super(id);
  }

  public ASTGenArity(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
