/* Generated By:JJTree: Do not edit this line. ASTGenParAttribs.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTGenParAttribs extends SimpleNode {
  public ASTGenParAttribs(int id) {
    super(id);
  }

  public ASTGenParAttribs(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
