/* Generated By:JJTree: Do not edit this line. ASTGenPar.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTGenPar extends SimpleNode {
  public ASTGenPar(int id) {
    super(id);
  }

  public ASTGenPar(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
