/* Generated By:JJTree: Do not edit this line. ASTGenConstraints.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTGenConstraints extends SimpleNode {
  public ASTGenConstraints(int id) {
    super(id);
  }

  public ASTGenConstraints(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
