/* Generated By:JJTree: Do not edit this line. ASTHexByte.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTHexByte extends SimpleNode {
  public ASTHexByte(int id) {
    super(id);
  }

  public ASTHexByte(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
