/* Generated By:JJTree: Do not edit this line. ASTId.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTId extends SimpleNode {
  public ASTId(int id) {
    super(id);
  }

  public ASTId(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  private String name = null;
  
  public void setName(String s) {
      this.name = s;
  }
  
  public String getName() {
      return name;
  }
}
