/* Generated By:JJTree: Do not edit this line. ASTLabelOrOffset.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTLabelOrOffset extends SimpleNode {
  public ASTLabelOrOffset(int id) {
    super(id);
  }

  public ASTLabelOrOffset(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
