/* Generated By:JJTree: Do not edit this line. ASTLocalsSignature.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTLocalsSignature extends SimpleNode {
  public ASTLocalsSignature(int id) {
    super(id);
  }

  public ASTLocalsSignature(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
