/* Generated By:JJTree: Do not edit this line. ASTLabels.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTLabels extends SimpleNode {
  public ASTLabels(int id) {
    super(id);
  }

  public ASTLabels(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
