/* Generated By:JJTree: Do not edit this line. ASTMethodCall.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTMethodCall extends SimpleNode {
  public ASTMethodCall(int id) {
    super(id);
  }

  public ASTMethodCall(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
