/* Generated By:JJTree: Do not edit this line. ASTMethodHeader.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTMethodHeader extends SimpleNode {
  public ASTMethodHeader(int id) {
    super(id);
  }

  public ASTMethodHeader(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
