/* Generated By:JJTree: Do not edit this line. ASTNameValPairs.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTNameValPairs extends SimpleNode {
  public ASTNameValPairs(int id) {
    super(id);
  }

  public ASTNameValPairs(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
