/* Generated By:JJTree: Do not edit this line. ASTNativeType.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTNativeType extends SimpleNode {
  public ASTNativeType(int id) {
    super(id);
  }

  public ASTNativeType(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
