/* Generated By:JJTree: Do not edit this line. ASTNameValPair.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTNameValPair extends SimpleNode {
  public ASTNameValPair(int id) {
    super(id);
  }

  public ASTNameValPair(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
