/* Generated By:JJTree: Do not edit this line. ASTPinvAttr.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTPinvAttr extends SimpleNode {
  public ASTPinvAttr(int id) {
    super(id);
  }

  public ASTPinvAttr(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
