/* Generated By:JJTree: Do not edit this line. ASTParameters.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTParameters extends SimpleNode {
  public ASTParameters(int id) {
    super(id);
  }

  public ASTParameters(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
