/* Generated By:JJTree: Do not edit this line. ASTParam.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTParam extends SimpleNode {
  public ASTParam(int id) {
    super(id);
  }

  public ASTParam(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
