/* Generated By:JJTree: Do not edit this line. ASTPropHeader.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTPropHeader extends SimpleNode {
  public ASTPropHeader(int id) {
    super(id);
  }

  public ASTPropHeader(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
