/* Generated By:JJTree: Do not edit this line. ASTPropMember.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTPropMember extends SimpleNode {
  public ASTPropMember(int id) {
    super(id);
  }

  public ASTPropMember(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
