/* Generated By:JJTree: Do not edit this line. ASTResolutionScope.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTResolutionScope extends SimpleNode {
  public ASTResolutionScope(int id) {
    super(id);
  }

  public ASTResolutionScope(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
