/* Generated By:JJTree: Do not edit this line. ASTRealNumber.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTRealNumber extends SimpleNode {
  public ASTRealNumber(int id) {
    super(id);
  }

  public ASTRealNumber(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
