/* Generated By:JJTree: Do not edit this line. ASTScopeBlock.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTScopeBlock extends SimpleNode {
  public ASTScopeBlock(int id) {
    super(id);
  }

  public ASTScopeBlock(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
