/* Generated By:JJTree: Do not edit this line. ASTSEHBlock.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTSEHBlock extends SimpleNode {
  public ASTSEHBlock(int id) {
    super(id);
  }

  public ASTSEHBlock(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
