/* Generated By:JJTree: Do not edit this line. ASTSEHClause.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTSEHClause extends SimpleNode {
  public ASTSEHClause(int id) {
    super(id);
  }

  public ASTSEHClause(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
