/* Generated By:JJTree: Do not edit this line. ASTTypeBase2.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTTypeBase2 extends SimpleNode {
  public ASTTypeBase2(int id) {
    super(id);
  }

  public ASTTypeBase2(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
