/* Generated By:JJTree: Do not edit this line. ASTTypeBase.java */

package com.topcoder.services.compiler.util.MSILParser;

public class ASTTypeBase extends SimpleNode {
  public ASTTypeBase(int id) {
    super(id);
  }

  public ASTTypeBase(MSILParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MSILParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String getType() {
      for(int i =0  ; i < jjtGetNumChildren(); i++) {
          if(children[i] instanceof ASTInspectableType) {
                return ((ASTInspectableType)children[i]).getType();
          }
      }
      
      return null;
  }
}
